# Generated by Django 4.2.5 on 2023-09-10 00:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.IntegerField()),
                ("noise_level", models.IntegerField()),
                ("trend_coefficients", models.IntegerField(default=0)),
                ("missing_percentage", models.IntegerField(default=0)),
                ("outlier_percentage", models.IntegerField(default=0)),
                (
                    "cycle_component_amplitude",
                    models.IntegerField(default=0, editable=False),
                ),
                ("cycle_component_frequency", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "submitted"),
                            ("Running", "running"),
                            ("Succeeded", "succeeded"),
                            ("Failed", "failed"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonalityComponentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amplitude", models.CharField(max_length=50)),
                ("phase_shift", models.CharField(max_length=50)),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("Daily", "daily"),
                            ("Weekly", "weekly"),
                            ("Monthly", "monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frequency_multiplier", models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Simulator",
            fields=[
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("data_size", models.IntegerField(blank=True, default=0, null=True)),
                ("use_case_name", models.CharField(max_length=200)),
                (
                    "time_series_type",
                    models.CharField(
                        choices=[
                            ("Multiplicative", "multiplicative"),
                            ("Additive", "additive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "producer_type",
                    models.CharField(
                        choices=[("Kafka", "kafka"), ("CSV", "csv file")], max_length=20
                    ),
                ),
                (
                    "process_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.CharField(
                        default=None, editable=False, max_length=100, null=True
                    ),
                ),
                (
                    "datasets",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator_api.configuration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="configuration",
            name="seasonality_components",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="simulator_api.seasonalitycomponentdetails",
            ),
        ),
    ]
