# Generated by Django 4.2.5 on 2023-09-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("simulator_api", "0002_configuration_simulator_alter_simulator_datasets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="simulator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="simulator_api.simulator",
            ),
        ),
    ]
