# Generated by Django 4.2.5 on 2023-09-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0008_remove_simulator_datasets_configuration_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='simulator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='simulator_api.simulator'),
        ),
    ]
