# Generated by Django 4.2.5 on 2023-09-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0011_alter_configuration_simulator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='simulator',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cycle_component_amplitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='seasonality_components',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.seasonalitycomponentdetails'),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='datasets',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.configuration'),
        ),
    ]
