# Generated by Django 4.2.5 on 2023-09-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0013_alter_configuration_seasonality_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='simulator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='simulator_api.simulator'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cycle_component_amplitude',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='seasonality_components',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.seasonalitycomponentdetails'),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='datasets',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='simulator_api.configuration'),
        ),
    ]
