# Generated by Django 4.2.5 on 2023-09-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0014_configuration_simulator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalitycomponentdetails',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_instance', to='simulator_api.configuration'),
        ),
    ]
