# Generated by Django 4.2.5 on 2023-09-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0017_alter_seasonalitycomponentdetails_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='simulator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='simulator_api.simulator'),
        ),
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_instance', to='simulator_api.configuration'),
        ),
    ]
