# Generated by Django 4.2.5 on 2023-09-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0018_alter_configuration_simulator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='seasonality_components',
        ),
        migrations.RemoveField(
            model_name='simulator',
            name='datasets',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='simulator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulator'),
        ),
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.configuration'),
        ),
    ]
