# Generated by Django 4.2.5 on 2023-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0020_alter_simulator_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='cycle_component_amplitude',
            field=models.IntegerField(editable=False),
        ),
    ]
