# Generated by Django 4.2.5 on 2023-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0022_simulator_datasets_alter_configuration_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='amplitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='phase_shift',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='simulator',
            name='datasets',
        ),
        migrations.AddField(
            model_name='simulator',
            name='datasets',
            field=models.ManyToManyField(default=None, related_name='configs', to='simulator_api.configuration'),
        ),
    ]
