# Generated by Django 4.2.5 on 2023-09-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0023_alter_seasonalitycomponentdetails_amplitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='seasonality_components',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulator_api.seasonalitycomponentdetails'),
        ),
    ]
