# Generated by Django 4.2.5 on 2023-09-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0026_alter_seasonalitycomponentdetails_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='simulator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='simulator_api.simulator'),
        ),
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='simulator_api.configuration'),
        ),
    ]
