# Generated by Django 4.2.5 on 2023-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0027_alter_configuration_simulator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='name',
            field=models.CharField(default='simulator', max_length=50, unique=True),
        ),
    ]
