# Generated by Django 4.2.5 on 2023-09-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0028_simulator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulator',
            name='name',
        ),
    ]
