# Generated by Django 4.2.5 on 2023-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0029_remove_simulator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='status',
        ),
        migrations.AddField(
            model_name='simulator',
            name='name',
            field=models.CharField(default='simulator', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='status',
            field=models.CharField(choices=[('Submitted', 'submitted'), ('Running', 'running'), ('Succeeded', 'succeeded'), ('Failed', 'failed')], default='Submitted', editable=False, max_length=100),
        ),
    ]
