# Generated by Django 4.2.5 on 2023-09-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0030_remove_configuration_status_simulator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='frequency',
            field=models.CharField(choices=[('1D', '1D'), ('10T', '10T'), ('30T', '30T'), ('1H', '1H'), ('6H', '6H'), ('8H', '8H')], max_length=20),
        ),
    ]
