# Generated by Django 4.2.5 on 2023-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0031_alter_configuration_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalitycomponentdetails',
            name='phase_shift',
            field=models.FloatField(max_length=10),
        ),
    ]
