# Generated by Django 4.2.5 on 2023-09-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0032_alter_seasonalitycomponentdetails_phase_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='cycle_component_amplitude',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
