# Generated by Django 4.2.5 on 2023-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0033_alter_configuration_cycle_component_amplitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='cycle_component_amplitude',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
