# Generated by Django 4.2.5 on 2023-09-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0034_alter_configuration_cycle_component_amplitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='metadata',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
