# Generated by Django 4.1.7 on 2023-09-22 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simulator_api", "0037_alter_configuration_missing_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="seasonality_components",
        ),
        migrations.RemoveField(
            model_name="simulator",
            name="datasets",
        ),
    ]
